# Site settings
title: CLJSJS
email: martinklepsch@googlemail.com
description: > # this means to ignore newlines until "baseurl:"
  CLJSJS provides an easy way for ClojureScript developers to depend
  on Javascript libraries.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cljsjs.github.io"
# twitter_username: jekyllrb
github_username: cljsjs

# Build settings
markdown: kramdown
